name: Mainframe pipeline

on:
  push:
    branches:
      - main

env:
  BACKEND_SERVICE: ${{ secrets.BACKEND_SERVICE }}
  FRONTEND_SERVICE: ${{ secrets.FRONTEND_SERVICE }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: ${{ secrets.REGION }}
  REACT_APP_NGROK_URL: ${{ secrets.REACT_APP_NGROK_URL }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

jobs:
  notify-telegram:
    name: Notify telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: |
            New changes: [${{ github.event.commits[0].message }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            Author: ${{ github.actor }}
            Repo: ${{ github.repository }}
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
  changes:
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            backend:
              - 'Dockerfile'
              - 'src/mainframe/**'
              - 'tests/**'
            frontend:
              - 'frontend/**'

  pre-commit:
    name: pre-commit (w/o migrations check)
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ (needs.changes.outputs.backend == 'true') }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
      - name: Installing dev dependencies for migration check
        run: uv sync
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
        env:
          ENV: ci
          SKIP: migrations-check

  safety-cli:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ (needs.changes.outputs.backend == 'true') }}
    steps:
      - uses: actions/checkout@main
      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@d3575b14a5cf597e34d5f7c420d2d5b4a84df410
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
          args: -i 59234 --detailed-output

  tests:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - safety-cli
    if: ${{ (needs.changes.outputs.backend == 'true') }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
      - name: Run CI
        run: uv run poe ci
      - name: Upload coverage report
        # make coverage.xml available to other jobs (e.g. sonar scan)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download coverage from tests job
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  backend-deploy:
    name: BE - Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - sonarqube
    steps:
      - name: Notify BE start deployment
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: Mainframe - Starting BE deploy
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@a61909d048e0be579b6c15b27088d19668493851
        with:
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba

      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag="$RUN_REGION-docker.pkg.dev/$PROJECT_ID/mainframe-backend/$BACKEND_SERVICE:$GITHUB_SHA" \
            --gcs-log-dir="gs://build-backend-logs"

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$BACKEND_SERVICE" \
            --quiet \
            --region "$RUN_REGION" \
            --image "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/mainframe-backend/$BACKEND_SERVICE:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
      - name: Notify
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: Mainframe - BE deployed successfully ðŸš€
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}

  frontend-build:
    name: FE - Build
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Notify FE start deployment
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: |
            [Mainframe](${{ github.event.workflow_job.html_url }}) - Starting FE deploy
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - name: Use cached node_modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        working-directory: frontend
        run: npm install --frozen-lockfile --ignore-scripts
        env:
          CI: true

      - name: Build Development
        working-directory: frontend
        run: npm run build
        env:
          CI: false

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: frontend/build

  frontend-deploy:
    name: FE - Deploy
    needs: frontend-build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: frontend/.docker/build

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@a61909d048e0be579b6c15b27088d19668493851
        with:
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba

      # Build and push image to Google Container Registry
      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag="$RUN_REGION-docker.pkg.dev/$PROJECT_ID/mainframe-frontend/$FRONTEND_SERVICE:$GITHUB_SHA" \
            --gcs-log-dir="gs://build-frontend-logs"
        working-directory: frontend/.docker

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$FRONTEND_SERVICE" \
            --quiet \
            --region "$RUN_REGION" \
            --image "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/mainframe-frontend/$FRONTEND_SERVICE:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --set-env-vars "REACT_APP_NGROK_URL=$REACT_APP_NGROK_URL,REACT_APP_API_URL=$REACT_APP_API_URL"
      - name: Notify
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: markdown
          message: Mainframe - FE deployed successfully ðŸš€
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
